"""add description column to products table

Revision ID: 781e5a947eef
Revises: 6a3f7f472581
Create Date: 2023-01-05 22:16:54.731388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "781e5a947eef"
down_revision = "6a3f7f472581"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "description",
                sa.Text(),
                server_default="",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.drop_column("description")

    # ### end Alembic commands ###
